# Generated by Django 3.2.7 on 2022-03-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('C', 'Contact'), ('S', 'Sharing'), ('T', 'Team')], max_length=3),
        ),
    ]
