# Generated by Django 3.2.7 on 2022-03-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_room_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='check_in',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_out',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='beds',
            new_name='personcapacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
    ]
